version: 2.1

# Importing orbs for Docker and Heroku
orbs:
  docker: circleci/docker@2.1.1
  # heroku: circleci/heroku@3.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build with Maven Wrapper
          command: ./mvnw clean package

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./mvnw test
  dockerize:
    docker:
      - image: circleci/openjdk:11-jdk  # Java-based image for Dockerization
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          # name: SCTP Group 1 Docker Assignment
          image: khairula86/sctpgrp1dockerassignment
          tag: latest
      - docker/push:
          image: khairula86/sctpgrp1dockerassignment
          tag: latest
          
workflows:
  version: 2
  ci_flow:
    when:
      branches:
        only:
          - develop
    jobs:
      - build
      - test

  cicd_flow:
    when:
      branches:
        only:
          - release
    jobs:
      - build
      - test
      - dockerize:
          requires:
            - test
      - deploy:
          requires:
            - dockerize