# version: 2.1

# # Importing orbs for Docker and Heroku
# orbs:
#   docker: circleci/docker@2.1.1
#   heroku: circleci/heroku@2.0.0

# jobs:
#   build:
#     docker:
#      - image: cimg/openjdk:17.0
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Build with Maven Wrapper
#           command: ./mvnw clean package

#   # test:
#   #   docker:
#   #     - image: cimg/openjdk:17.0
#   #   steps:
#   #     - checkout
#   #     - run:
#   #         name: Run Tests
#   #         command: ./mvnw test

# # Commented out other jobs for now to troubleshoot build and test
# #  dockerize:
# #    docker:
# #      - image: circleci/openjdk:11-jdk  # Java-based image for Dockerization
# #    steps:
# #      - checkout
# #      - setup_remote_docker
# #      - docker/build:
# #          # name: SCTP Group 1 Docker Assignment
# #          image: khairula86/sctpgrp1dockerassignment
# #          tag: latest
# #      - docker/push:
# #          image: khairula86/sctpgrp1dockerassignment
# #          tag: latest

# #  deploy:
# #    docker:
# #      - image: cimg/base:stable
# #    steps:
# #      - setup_remote_docker
# #      - heroku/install
# #      - checkout
# #      - run:
# #          name: Heroku Container Push
# #          command: |
# #            heroku container:login
# #            heroku stack:set container -a sctpgrp1-dockerassignment
# #            heroku container:push web -a sctpgrp1-dockerassignment
# #            heroku container:release web -a sctpgrp1-dockerassignment

# workflows:
#   version: 2
#   ci_flow:
#     when:
#       branches:
#         only:
#           - develop
#     jobs:
#       - build
#       # - test

# # Commented out cicd_flow for now
# #  cicd_flow:
# #    when:
# #      branches:
# #        only:
# #          - release
# #    jobs:
# #      - build
# #      - test
# #      - dockerize:
# #          requires:
# #            - test
# #      - deploy:
# #          requires:
# #            - dockerize

version: 2.1

# Importing orbs for Docker and Heroku
orbs:
  docker: circleci/docker@2.1.1
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build with Maven Wrapper
          command: ./mvnw clean package

  test:
    docker:
       - image: circleci/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./mvnw test

  dockerize:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t khairula86/sctpgrp1dockerassignment:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push khairula86/sctpgrp1dockerassignment:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            heroku git:remote -a sctpgrp1-dockerassignment
            git push heroku main

workflows:
  version: 2
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          filters:
            branches:
              only:
                - develop

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - test:
          filters:
            branches:
              only:
                - release
      - dockerize:
          requires:
            - test
          filters:
            branches:
              only:
                - release
      - deploy:
          requires:
            - dockerize
          filters:
            branches:
              only:
                - release