version: 2.1

# Importing orbs for Docker and Heroku
orbs:
  docker: circleci/docker@2.1.1
  heroku: circleci/heroku@3.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build with Maven Wrapper
          command: ./mvnw clean package

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./mvnw test
deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - heroku/deploy:
        app_name: